server {
    listen       80;
    server_name  _;

    root   /usr/share/nginx/html;

    # / -> /dashboard.html
    location = / {
        return 302 /dashboard.html;
    }

    location / {
        index  dashboard.html;
        try_files $uri $uri/ =404;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }
}
